services:
  - type: web
    name: xlsm-license-server
    env: python
    plan: starter
    buildCommand: ""
    startCommand: python license_server.py
    disk:
      name: data-disk
      mountPath: /mnt/data
      sizeGB: 1
