services:
  - type: web
    name: xlsm-license-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python license_server.py"
    autoDeploy: true
    disk:
      name: license-storage
      mountPath: /mnt/data
      sizeGB: 1
